version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker      # https://circleci.com/docs/2.0/building-docker-images/
      - run: make docker-minimum
      - run: make docker-medium
      - run: make docker-maximum
      - run:
          name: Publish Docker images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push ocrd/all:minimum
            docker push ocrd/all:medium
            docker push ocrd/all:maximum
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
