version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker      # https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Build Docker images
          command: |
            make dockers
      - run:
          name: Build Docker images
          command: |
            make dockers
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push ocrd/all:minimum
            docker push ocrd/all:medium
            docker push ocrd/all:maximum
workflows:
  version: 2
  build-master:
    jobs:
      - build #:
          # filters:
            # branches:
              # only: master
